apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  project: default
  source:
    path: ./project/helm
    repoURL: https://github.com/patrickbrus/TechTrends.git
    targetRevision: master
    helm:
      releaseName: techtrends
      valueFiles:
        - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"