namespace: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image: 
  repository: ga63qes/techtrends
  tag: latest 
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits: 
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbePath: /healthz
readinessProbePath: /healthz