namespace: staging

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image: 
  repository: ga63qes/techtrends
  tag: latest 
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits: 
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbePath: /healthz
readinessProbePath: /healthz